name: Update CPAN module manually.

env:
  perl-version: "5.40"

permissions:
  contents: write
  pull-requests: write

on:
  workflow_dispatch:
    inputs:
      module:
        description: The updating module name.
        type: string
        required: true

jobs:
  bump-cpanfile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - uses: ./.github/composite/update-cpan-module
        with:
          perl-version: ${{ inputs.perl-version }}
          module: ${{ inputs.module }}
